# Generated by Django 5.1.7 on 2025-03-14 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0002_customlabel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thread_url', models.URLField(unique=True)),
                ('username', models.CharField(max_length=255)),
                ('profile_url', models.URLField(blank=True, null=True)),
                ('messages', models.JSONField(default=list)),
                ('last_message_timestamp', models.DateTimeField()),
                ('label', models.CharField(max_length=255)),
            ],
        ),
    ]
