# Generated by Django 5.1.7 on 2025-03-15 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0003_conversation'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpamCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('profile_url', models.URLField(blank=True, null=True, unique=True)),
                ('spam_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='conversation',
            name='last_message_timestamp',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='messages',
            field=models.JSONField(default=list, null=True),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='username',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
